---
title: "First Knit"
author: "Alondra"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I went to Palmdale High School. I graduated in 2018. English classes were always easier for me then math. I struggled a lot in math but managed to pass. My best subject was English, I always passed with A's and B's. 

     


## Your computer and your and its capability?  
For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
The computer I will be using at home is a Hp Microsoft. I would rate myself about a 7.5 on my knowledge with computers. My internet connection at home is very basic, It chooses to be fast when it feels like it. 
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I have a few nicknames that I have been called. My older sister calls me Coco, My little sister and boyfriend sometimes call me Atontaa, and my old friends call me Alo. I prefer to be called Alo by peers in my class if they can not pronoun my name correctly.
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
What I want to achieve in life is to become a successful therapist and create a good life for my future family. One college subject that I find very interested that is Psychology and Children Development. The degree I'm trying to achieve is a Bachelors and Master degree.
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
The only foreign country I've gone to is Mexico. I plan to travel more in the future, I would like to go to Spain or Italy one day. I have never been in the military and I have no thoughts of it because I feel like I would not be able to survive Bootcamp.




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
This is my second time taking Math 115, I drop the class the first time I took it due to a teacher insulting me saying there was no way I could pass her class. I was very upset because instead of offering help she told me to just drop her class. I did not know that Math 115 is a G.E.D requirement and Math 116 was statistics. I need at least a B to attain my education plans that I have. My plan is to transfer to a 4 year University by Fall 2024.  
   
 






  




